version: '3.9'

services:

  gestifysolution-server-dev:
    extends:
      file: ../docker/docker-compose.base.yml
      service: gestifysolution-server-base
    build: 
      context: .
      args:
        ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
      dockerfile: dockerfile.devcontainer
    working_dir: /workspace/gestifysolution-server
    volumes:
      - ../:/workspace/gestifysolution-server
    networks:
      - backend-dev
    env_file:
      - .env
    depends_on:
      - gestifysolution-db-dev
    command: sleep infinity
    
  gestifysolution-db-dev:
    extends:
      file: ../docker/docker-compose.base.yml
      service: gestifysolution-db-base
    volumes:
      - ../docker/provisions/mysql/init:/docker-entrypoint-initdb.d
      - gestifysolution-db-data-dev:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DATABASE_NAME}
    networks:
      - backend-dev
  
  gestifysolution-keycloak-dev:
    extends:
      file: ../docker/docker-compose.base.yml
      service: gestifysolution-keycloak-base
    environment:
      - KC_DB_URL=jdbc:mysql://gestifysolution-db-dev:3306/${KEYCLOAK_DATABASE_NAME}
    depends_on:
      - gestifysolution-db-dev
    networks:
      - backend-dev
    command:
      - "start-dev"

volumes:
  gestifysolution-db-data-dev:

networks:
  backend-dev:
    driver: bridge